### ISSUE TITLE
GRBL status warning

### ISSUE THREAD

**Issue by yagizzha** [flynneva/grbl_ros#116]
![image](https://user-images.githubusercontent.com/88779645/144198401-e0235fc6-088c-48d0-86dc-7d6d20a3ed72.png)
getting this warning every time i send a command , takes 2 of same command to move to place i want , also 
![image](https://user-images.githubusercontent.com/88779645/144198752-868f4da8-488e-4074-855f-338071babf84.png)
cant echo the position 

what can be causing this ? is it possible for grbl version to be the problem ?

**Comment by flynneva** [comment]
What version of grbl do you have?

**Comment by yagizzha** [comment]
i am using 1.1 version

**Comment by flynneva** [comment]
@yagizzha so that is the same as what I have locally and I've tested this package with that `grbl` version.

Have you used your `grbl` CNC before with another program like [openbuilds-control](https://openbuildspartstore.com/openbuilds-control/) and confirmed your device is functional?

Also, are you following the `README` instructions to first unlock and then run a gcode command?

**Comment by yagizzha** [comment]
i havent used it with anything else , tho it gives expected results when i put commands through arduino . i can send gcode commands but what i receive back in ros seems to not be what it expects
